language: node_js
node_js:
    - '11'
cache:
    directories:
        - node_modules

branches:
    only:
        - master

install:
    - npm install -g yarn

before_script:
    - yarn global add nyc
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

script:
    # - npm test
    # - npm run build
    - yarn install
    - yarn build
    - yarn test --coverage && cat ./coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: build
    fqdn: dnd-player.com
    on:
        branch: master
