language: node_js
node_js:
    - '11'
cache:
    directories:
        - node_modules

branches:
    only:
        - master

install:
    - npm install -g yarn

script:
    # - npm test
    # - npm run build
    - yarn install
    - yarn build
    - yarn test

jobs:
    include:
        - stage: Produce Coverage
          node_js: node
          script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: build
    fqdn: dnd-player.com
    on:
        branch: master
