
language: node_js
node_js:
  - "11"
cache:
  directories:
  - node_modules

branches:
  only:
    - master

install:
  - npm install -g yarn

script:
  # - npm test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: gh_pages